# tmux configuration

# Fix scrolling issues with splits
set -ga terminal-overrides ',*:smcup@:rmcup@'
set -g mouse on

# Pane switching (triggered by iTerm2 CMD+[ and CMD+])
bind -n M-p select-pane -t :.-
bind -n M-n select-pane -t :.+

# Show help in a popup instead of taking over the terminal
bind-key ? display-popup -h 90% -w 90% -E "tmux list-keys -N | less"

# Toggle status bar with prefix + b
bind-key b set-option status
